name: Create Release on Tag Push

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Setup yarn
        run: npm i -g yarn

      # Get yarn store directory
      - name: Get yarn store directory
        id: yarn-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(yarn cache dir)" >> $GITHUB_OUTPUT

      # Setup yarn cache
      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build for production
      - name: Build for production
        run: yarn build

      # Package as zip file
      - name: Zip it
        run: zip -r dist.zip dist/

      # Get changelog
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get CHANGELOGS
        run: python ./scripts/release_note.py
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./result.txt
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'dev') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist.zip

      - uses: JS-DevTools/npm-publish@v3
        if: ${{ ! (contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'dev')) }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
